services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: myredis
    volumes:
      - redis-data:/data

  news-api:
    build:
      context: ./news-api
      dockerfile: Dockerfile
    image: news-api:latest
    container_name: news-api
    depends_on:
      - kafka
      - redis
    environment:
      KAFKA_SERVER: kafka:29092
      REDIS_SERVER: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: myredis
    ports:
      - "8080:8080"

  worker-service:
    build:
      context: ./worker-service
      dockerfile: Dockerfile
    image: worker-service:latest
    container_name: worker-service
    depends_on:
      - kafka
      - redis
    environment:
      KAFKA_SERVER: kafka:29092
      REDIS_SERVER: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: myredis
      MEDIASTACK_URI: http://api.mediastack.com/v1/news
      MEDIASTACK_API_KEY: 9b52bae7d274225d5808b1778f4fb37d
    ports:
      - "8081:8081"

  crypto-fetcher-service:
    build:
      context: ./crypto-fetcher-service
      dockerfile: Dockerfile
    image: crypto-fetcher-service:latest
    container_name: crypto-fetcher-service
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: kafka:29092
    ports:
      - "8083:8083"

  price-processor-service:
    build:
      context: ./price-processor-service
      dockerfile: Dockerfile
    image: price-processor-service:latest
    container_name: price-processor-service
    depends_on:
      - kafka
      - redis
    environment:
      KAFKA_SERVER: kafka:29092
      REDIS_SERVER: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: myredis
    ports:
      - "8084:8084"

volumes:
  redis-data: