server:
  port: 8081

spring:
  application:
    name: worker-service
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
  data:
    redis:
      host: ${REDIS_SERVER}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      service: ${DD_SERVICE:worker-service}
      env: ${DD_ENV:docker-local}
  endpoint:
    health:
      show-details: always

mediastack:
  uri: ${MEDIASTACK_URI}
  api-key: ${MEDIASTACK_API_KEY}
  countries: us
  limit: 25