server:
  port: 8085

spring:
  application:
    name: alert-service

  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:29092}
    consumer:
      group-id: alert-service-group

  data:
    redis:
      host: ${REDIS_SERVER:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:myredis}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      service: ${DD_SERVICE:alert-service}
      env: ${DD_ENV:docker-local}
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.alexlondon07: DEBUG
    org.apache.kafka: WARN